# Generated by Django 6.0.1 on 2026-01-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradely', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
