# Generated by Django 6.0.1 on 2026-01-26 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradely', '0002_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=50)),
                ('school_year', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='classrooms', to='gradely.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradely.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'FACULTY'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('total_score', models.IntegerField(default=100)),
                ('answer_key', models.JSONField(blank=True, default=dict)),
                ('mean_score', models.FloatField(blank=True, default=0.0)),
                ('min_score', models.FloatField(blank=True, default=0.0)),
                ('max_score', models.FloatField(blank=True, default=0.0)),
                ('attendees_count', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='gradely.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_answers', models.JSONField(blank=True, default=dict)),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='gradely.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='gradely.student')),
            ],
            options={
                'unique_together': {('quiz', 'student')},
            },
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
