# Generated by Django 6.0.1 on 2026-01-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradely', '0003_classroom_quiz_quizresult_delete_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Pedro', max_length=100),
            preserve_default=False,
        ),
    ]
