# Generated by Django 6.0.1 on 2026-01-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradely', '0004_remove_student_first_name_remove_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade_level',
            field=models.IntegerField(choices=[(0, 'Kinder'), (1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')], default=6, help_text='The grade/year level this subject belongs to.'),
        ),
    ]
