# Generated by Django 6.0.1 on 2026-02-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradely', '0005_subject_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='scanned_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
